language: objective-c
before_install: 
script:
   - xcodebuild -project ex_variable.xcodeproj -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
   - xcodebuild -project ex_variable.xcodeproj -scheme ex_variable -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test
after_success: 
env:
  global:
  - secure: dKSTmbCPlQMsKuaixAqzgTLvTG8wZoLXGZqKQhBOzCHbyEP/kX6WCQvhyITDFikRQHnu/QlEBRyCUsZ2tCZJJ5+buwzI7elXZGRQCLFukMsOVLi4NnnfHP+QNXhaxESzWJDdEVOEeNSDQ0D8lvMdOWE8O7WgmwZqaZNTR/HrvAc=
  - secure: kkVZsynYkYzbLyYQcyOOJoPym97/WXiR0UhV1zjsqMM5a2qY5b88pMPbRxC8qJJ5vQdRrb502/AluElTo1szGmdBwG7yURoF2Vp5yfNSnyBzpDKQ97gNmo39a36mka9lRr555m/dEhrcqnWhNTGV1CSEQ0bxZNYBltilEQ0KGJE=
